/* Copyright (C) 2019 Nunuhara Cabbage <nunuhara@haniwa.technology>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://gnu.org/licenses/>.
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "system4.h"
#include "instructions.h"

// JMP = instruction that modifies the instruction pointer
// OP  = everything else
#define OP(code, args)  [code] = { .opcode = code, .name = #code , .nr_args = args, .ip_inc = 2 + args * 4 }
#define JMP(code, args) [code] = { .opcode = code, .name = #code , .nr_args = args, .ip_inc = 0 }

const struct instruction instructions[NR_OPCODES] = {
	OP(PUSH, 1),
        OP(POP, 0),
        OP(REF, 0),
        OP(REFREF, 0),
        OP(PUSHGLOBALPAGE, 0),
        OP(PUSHLOCALPAGE, 0),
        OP(INV, 0),
        OP(NOT, 0),
        OP(COMPL, 0),
        OP(ADD, 0),
        OP(SUB, 0),
        OP(MUL, 0),
        OP(DIV, 0),
        OP(MOD, 0),
        OP(AND, 0),
        OP(OR, 0),
        OP(XOR, 0),
        OP(LSHIFT, 0),
        OP(RSHIFT, 0),
        OP(LT, 0),
        OP(GT, 0),
        OP(LTE, 0),
        OP(GTE, 0),
        OP(NOTE, 0),
        OP(EQUALE, 0),
        OP(ASSIGN, 0),
        OP(PLUSA, 0),
        OP(MINUSA, 0),
        OP(MULA, 0),
        OP(DIVA, 0),
        OP(MODA, 0),
        OP(ANDA, 0),
        OP(ORA, 0),
        OP(XORA, 0),

        OP(LSHIFTA, 0),
        OP(RSHIFTA, 0),

        OP(F_ASSIGN, 0),
        OP(F_PLUSA, 0),
        OP(F_MINUSA, 0),
        OP(F_MULA, 0),
        OP(F_DIVA, 0),
        OP(DUP2, 0),
        OP(DUP_X2, 0),

        OP(CMP, 0),

        JMP(JUMP, 1),
        JMP(IFZ, 1),
        JMP(IFNZ, 1),
        JMP(RETURN, 0),
        JMP(CALLFUNC, 1),
        OP(INC, 0),
        OP(DEC, 0),
        OP(FTOI, 0),
        OP(ITOF, 0),
        OP(F_INV, 0),
        OP(F_ADD, 0),
        OP(F_SUB, 0),
        OP(F_MUL, 0),
        OP(F_DIV, 0),
        OP(F_LT, 0),
        OP(F_GT, 0),
        OP(F_LTE, 0),
        OP(F_GTE, 0),
        OP(F_NOTE, 0),
        OP(F_EQUALE, 0),
        OP(F_PUSH, 0),
        OP(S_PUSH, 1),
        OP(S_POP, 0),
        OP(S_ADD, 0),
        OP(S_ASSIGN, 0),
        OP(S_PLUSA, 0),
        OP(S_REF, 0),
        OP(S_REFREF, 0),
        OP(S_NOTE, 0),
        OP(S_EQUALE, 0),
        OP(SF_CREATE, 0),
        OP(SF_CREATEPIXEL, 0),
        OP(SF_CREATEALPHA, 0),

        OP(SR_POP, 0),
        OP(SR_ASSIGN, 0),
        OP(SR_REF, 0),
        OP(SR_REFREF, 0),
        OP(A_ALLOC, 0),
        OP(A_REALLOC, 0),
        OP(A_FREE, 0),
        OP(A_NUMOF, 0),
        OP(A_COPY, 0),
        OP(A_FILL, 0),
        OP(C_REF, 0),
        OP(C_ASSIGN, 0),
        OP(MSG, 0),
        OP(CALLHLL, 0),
        OP(PUSHSTRUCTPAGE, 0),
        OP(CALLMETHOD, 0),
        OP(SH_GLOBALREF, 1),
        OP(SH_LOCALREF, 1),
        OP(SWITCH, 0),
        OP(STRSWITCH, 0),
        OP(FUNC, 1),
        OP(_EOF, 1),
        OP(CALLSYS, 1),
        OP(SJUMP, 0),
        OP(CALLONJUMP, 0),
        OP(SWAP, 0),
        OP(SH_STRUCTREF, 0),
        OP(S_LENGTH, 0),
        OP(S_LENGTHBYTE, 0),
        OP(I_STRING, 0),
        OP(CALLFUNC2, 0),
        OP(DUP2_X1, 0),
        OP(R_ASSIGN, 0),
        OP(FT_ASSIGNS, 0),
        OP(ASSERT, 0),
        OP(S_LT, 0),
        OP(S_GT, 0),
        OP(S_LTE, 0),
        OP(S_GTE, 0),
        OP(S_LENGTH2, 0),
        OP(S_LENGTHBYTE2, 0),
        OP(NEW, 0),
        OP(DELETE, 0),
        OP(CHECKUDO, 0),
        OP(A_REF, 0),
        OP(DUP, 0),
        OP(DUP_U2, 0),
        OP(SP_INC, 0),
        OP(SP_DEC, 0),
        OP(ENDFUNC, 1),
        OP(R_EQUALE, 0),
        OP(R_NOTE, 0),
        OP(SH_LOCALCREATE, 0),
        OP(SH_LOCALDELETE, 0),
        OP(STOI, 0),
        OP(A_PUSHBACK, 0),
        OP(A_POPBACK, 0),
        OP(S_EMPTY, 0),
        OP(A_EMPTY, 0),
        OP(A_ERASE, 0),
        OP(A_INSERT, 0),
        OP(SH_LOCALINC, 1),
        OP(SH_LOCALDEC, 1),
        OP(SH_LOCALASSIGN, 2),
        OP(ITOB, 0),
        OP(S_FIND, 0),
        OP(S_GETPART, 0),
        OP(A_SORT, 0),
        OP(S_PUSHBACK, 0),
        OP(S_POPBACK, 0),
        OP(FTOS, 0),
        OP(S_MOD, 0),
        OP(S_PLUSA2, 0),
        OP(OBJSWAP, 0),
        OP(S_ERASE, 0),
        OP(SR_REF2, 0),
        OP(S_ERASE2, 0),
        OP(S_PUSHBACK2, 0),
        OP(S_POPBACK2, 0),
        OP(ITOLI, 0),
        OP(LI_ADD, 0),
        OP(LI_SUB, 0),
        OP(LI_MUL, 0),
        OP(LI_DIV, 0),
        OP(LI_MOD, 0),
        OP(LI_ASSIGN, 0),
        OP(LI_PLUSA, 0),
        OP(LI_MINUSA, 0),
        OP(LI_MULA, 0),
        OP(LI_DIVA, 0),
        OP(LI_MODA, 0),
        OP(LI_ANDA, 0),
        OP(LI_ORA, 0),
        OP(LI_XORA, 0),
        OP(LI_LSHIFTA, 0),
        OP(LI_RSHIFTA, 0),
        OP(LI_INC, 0),
        OP(LI_DEC, 0),
        OP(A_FIND, 0),
        OP(A_REVERSE, 0),
        OP(SH_SR_ASSIGN, 0),
        OP(SH_MEM_ASSIGN_LOCAL, 0),
        OP(A_NUMOF_GLOB_1, 0),
        OP(A_NUMOF_STRUCT_1, 0),
        OP(SH_MEM_ASSIGN_IMM, 0),
        OP(SH_LOCALREFREF, 0),
        OP(SH_LOCALASSIGN_SUB_IMM, 0),
        OP(SH_IF_LOC_LT_IMM, 0),
        OP(SH_IF_LOC_GE_IMM, 0),
        OP(SH_LOCREF_ASSIGN_MEM, 0),
        OP(PAGE_REF, 0),
        OP(SH_GLOBAL_ASSIGN_LOCAL, 0),
        OP(SH_STRUCTREF_GT_IMM, 0),
        OP(SH_STRUCT_ASSIGN_LOCALREF_ITOB, 0),
        OP(SH_LOCAL_ASSIGN_STRUCTREF, 0),
        OP(SH_IF_STRUCTREF_NE_LOCALREF, 0),
        OP(SH_IF_STRUCTREF_GT_IMM, 0),
        OP(SH_STRUCTREF_CALLMETHOD_NO_PARAM, 0),
        OP(SH_STRUCTREF2, 0),
        OP(SH_REF_STRUCTREF2, 0),
        OP(SH_STRUCTREF3, 0),
        OP(SH_STRUCTREF2_CALLMETHOD_NO_PARAM, 0),
        OP(SH_IF_STRUCTREF_Z, 0),
        OP(SH_IF_STRUCT_A_NOT_EMPTY, 0),
        OP(SH_IF_LOC_GT_IMM, 0),
        OP(SH_IF_STRUCTREF_NE_IMM, 0),
        OP(THISCALLMETHOD_NOPARAM, 0),
        OP(SH_IF_LOC_NE_IMM, 0),
        OP(SH_IF_STRUCTREF_EQ_IMM, 0),
        OP(SH_GLOBAL_ASSIGN_IMM, 0),
        OP(SH_LOCALSTRUCT_ASSIGN_IMM, 0),
        OP(SH_STRUCT_A_PUSHBACK_LOCAL_STRUCT, 0),
        OP(SH_GLOBAL_A_PUSHBACK_LOCAL_STRUCT, 0),
        OP(SH_LOCAL_A_PUSHBACK_LOCAL_STRUCT, 0),
        OP(SH_IF_SREF_NE_STR0, 0),
        OP(SH_S_ASSIGN_REF, 0),
        OP(SH_A_FIND_SREF, 0),
        OP(SH_SREF_EMPTY, 0),
        OP(SH_STRUCTSREF_EQ_LOCALSREF, 0),
        OP(SH_LOCALSREF_EQ_STR0, 0),
        OP(SH_STRUCTSREF_NE_LOCALSREF, 0),
        OP(SH_LOCALSREF_NE_STR0, 0),
        OP(SH_STRUCT_SR_REF, 0),
        OP(SH_STRUCT_S_REF, 0),
        OP(S_REF2, 0),
        OP(SH_REF_LOCAL_ASSIGN_STRUCTREF2, 0),
        OP(SH_GLOBAL_S_REF, 0),
        OP(SH_LOCAL_S_REF, 0),
        OP(SH_LOCALREF_SASSIGN_LOCALSREF, 0),
        OP(SH_LOCAL_APUSHBACK_LOCALSREF, 0),
        OP(SH_S_ASSIGN_CALLSYS19, 0),
        OP(SH_S_ASSIGN_STR0, 0),
        OP(SH_SASSIGN_LOCALSREF, 0),
        OP(SH_STRUCTREF_SASSIGN_LOCALSREF, 0),
        OP(SH_LOCALSREF_EMPTY, 0),
        OP(SH_GLOBAL_APUSHBACK_LOCALSREF, 0),
        OP(SH_STRUCT_APUSHBACK_LOCALSREF, 0),
        OP(SH_STRUCTSREF_EMPTY, 0),
        OP(SH_GLOBALSREF_EMPTY, 0),
        OP(SH_SASSIGN_STRUCTSREF, 0),
        OP(SH_SASSIGN_GLOBALSREF, 0),
        OP(SH_STRUCTSREF_NE_STR0, 0),
        OP(SH_GLOBALSREF_NE_STR0, 0),
        OP(SH_LOC_LT_IMM_OR_LOC_GE_IMM, 0),
        OP(A_SORT_MEM, 0),
        OP(DG_ADD, 0),
        OP(DG_SET, 0),
        OP(DG_CALL, 0),
        OP(DG_NUMOF, 0),
        OP(DG_EXIST, 0),
        OP(DG_ERASE, 0),
        OP(DG_CLEAR, 0),
        OP(DG_COPY, 0),
        OP(DG_ASSIGN, 0),
        OP(DG_PLUSA, 0),
        OP(DG_POP, 0),
        OP(DG_NEW_FROM_METHOD, 0),
        OP(DG_MINUSA, 0),
        OP(DG_CALLBEGIN, 0),
        OP(DG_NEW, 0),
        OP(DG_STR_TO_METHOD, 0),
};
